version: "3.2"

services:
  api:
    build:
      context: api/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./api:/api
    environment:
      - DB_HOST=db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  client:
    build:
      context: client/
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/app
      - "/usr/app/node_modules"
    ports:
      - "8080:8080"
    depends_on:
      - api
