# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI-client

on:
  push:
    branches: [master]
    paths:
      - "client/**"
  pull_request:
    branches: [master]
    paths:
      - "client/**"

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.15.1"
      - name: Build api docker
        run: docker-compose up -d client
      - name: Run tests
        run: docker-compose run client yarn test:unit

  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.4
        with:
          projectBaseDir: client
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLIENT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [build_and_tests, code_quality]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "client/"
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_SECRET}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag rogerioo/trabalho-individual-2020-1:client_latest

      - name: Docker Push
        run: docker push rogerioo/trabalho-individual-2020-1:client_latest
